bsdinstall: add support for -X

diff --git a/bsdinstall b/bsdinstall
--- a/bsdinstall
+++ b/bsdinstall
@@ -34,6 +34,21 @@
 export DEBUG_SELF_INITIALIZE=
 export DEBUG_INITIALIZE_FILE=
 
+# When common.subr is included, it automatically scans "$@" for `-d' and/or
+# `-D file' arguments to conditionally enable debugging. Similarly, when
+# dialog.subr is included, it automatically scans "$@" for `-X' and/or `-S'.
+# To prevent this scanning from becoming confused by extra options, define
+# any/all extra arguments to use in the optstring to getopts when scanning
+# for dedicated options such as those described.
+#
+# NOTE: This needs to be declared before including `common.subr'.
+# NOTE: You really only need to list flags that require an argument as unknown
+#       flags are silently accepted unless they take an argument (in which case
+#       the following argument will terminate option processing unless it looks
+#       like a flag).
+#
+GETOPTS_EXTRA="X"
+
 : ${PREFIX:="/usr"}; export PREFIX
 : ${BSDCFG_SHARE:="$PREFIX/share/bsdconfig"}
 . $BSDCFG_SHARE/common.subr || exit 1
@@ -42,6 +57,7 @@ export DEBUG_INITIALIZE_FILE=
 
 : ${TMPDIR:=$(mktemp -d)}; export TMPDIR
 
+: ${BSDINSTALL_ARGS=}; export BSDINSTALL_ARGS
 : ${BSDINSTALL_TMPETC="${TMPDIR}/bsdinstall_etc"}; export BSDINSTALL_TMPETC
 : ${BSDINSTALL_TMPBOOT="${TMPDIR}/bsdinstall_boot"}; export BSDINSTALL_TMPBOOT
 : ${PATH_FSTAB="$BSDINSTALL_TMPETC/fstab"}; export PATH_FSTAB
@@ -51,13 +67,34 @@ export DEBUG_INITIALIZE_FILE=
 
 export debugFile="${debugFile-${BSDINSTALL_LOG-${TMPDIR}/bsdinstall_log}}"
 
+############################################################ USAGE
+
+usage()
+{
+	echo "Usage: bsdinstall [-$GETOPTS_EXTRA$GETOPTS_STDARGS][target][...]" 1>&2
+	echo "  -X	Start in graphical mode" 1>&2
+	echo "  -d	Enable debugging output" 1>&2
+	echo "  -D	Save debugging output to a file" 1>&2
+	return 1
+}
+
 ############################################################ MAIN
 
 #
 # Process command-line arguments
 #
-while getopts $GETOPTS_STDARGS ignored; do
-	: just skipping known flags
+USE_XDIALOG=
+while getopts "$GETOPTS_EXTRA$GETOPTS_STDARGS" name; do
+	case "$name" in
+		X)
+			BSDINSTALL_ARGS="-X $BSDINSTALL_ARGS"
+			: ${DIALOG="Xdialog"}; export DIALOG
+			;;
+		'?')
+			usage
+			exit $?
+			;;
+	esac
 done
 shift $(( $OPTIND - 1 ))
 
@@ -71,19 +108,19 @@ VERB="${1:-auto}"; shift
 f_quietly f_debug_init
 f_isset debugFile || debug=
 
-f_dprintf "Running installation step: %s %s" "$VERB" "$*"
+f_dprintf "Running installation step: %s %s" "$VERB" "$BSDINSTALL_ARGS" "$*"
 if [ "$debug" ]; then
 	case "$debugFile" in
 	# If NULL, send errors to the bit-bucket
-	"") exec "$BSDINSTALL_SCRIPTS/$VERB" "$@" 2> /dev/null ;;
+	"") exec "$BSDINSTALL_SCRIPTS/$VERB" $BSDINSTALL_ARGS "$@" 2> /dev/null ;;
 	# If begins with `+', send errors to both terminal and file (no `+')
-	+*) exec "$BSDINSTALL_SCRIPTS/$VERB" "$@" \
+	+*) exec "$BSDINSTALL_SCRIPTS/$VERB" $BSDINSTALL_ARGS "$@" \
 		2>&1 >&$TERMINAL_STDOUT_PASSTHRU | tee "${debugFile#+}" ;;
 	# Otherwise, just send errors to the file specified
-	*) exec "$BSDINSTALL_SCRIPTS/$VERB" "$@" 2>> "$debugFile"
+	*) exec "$BSDINSTALL_SCRIPTS/$VERB" $BSDINSTALL_ARGS "$@" 2>> "$debugFile"
 	esac
 else
-	exec "$BSDINSTALL_SCRIPTS/$VERB" "$@" 2> /dev/null
+	exec "$BSDINSTALL_SCRIPTS/$VERB" $BSDINSTALL_ARGS "$@" 2> /dev/null
 fi
 
 ################################################################################
