bsdinstall: wrap bsdinstall(1) everywhere
This is only meant for testing.

diff --git a/scripts/auto b/scripts/auto
--- a/scripts/auto
+++ b/scripts/auto
@@ -78,7 +78,7 @@ error()
 	local prompt="${1:+$1\n\n}$msg_an_installation_step_has_been_aborted"
 	local hline="$hline_arrows_tab_space_enter"
 
-	[ -f "$PATH_FSTAB" ] && bsdinstall umount
+	[ -f "$PATH_FSTAB" ] && ./bsdinstall umount
 
 	local height width
 	f_dialog_buttonbox_size height width \
@@ -150,10 +150,10 @@ mkdir $BSDINSTALL_TMPETC
 [ -f $PREFIX/libexec/bsdinstall/local.pre-everything ] && f_dprintf "Running local.pre-everything" && sh $PREFIX/libexec/bsdinstall/local.pre-everything "$BSDINSTALL_CHROOT"
 
 trap true SIGINT	# This section is optional
-[ -z "$BSDINSTALL_SKIP_KEYMAP" ] && bsdinstall keymap
+[ -z "$BSDINSTALL_SKIP_KEYMAP" ] && ./bsdinstall keymap
 
 trap error SIGINT	# Catch cntrl-C here
-if [ -z "$BSDINSTALL_SKIP_HOSTNAME" ]; then bsdinstall hostname || error "Set hostname failed"; fi
+if [ -z "$BSDINSTALL_SKIP_HOSTNAME" ]; then ./bsdinstall hostname || error "Set hostname failed"; fi
 
 export DISTRIBUTIONS="${DISTRIBUTIONS:-base.txz kernel.txz}"
 if [ -f $BSDINSTALL_DISTDIR/MANIFEST ]; then
@@ -183,7 +183,7 @@ done
 
 if [ -n "$FETCH_DISTRIBUTIONS" -a -n "$BSDINSTALL_CONFIGCURRENT" ]; then
 	$BSDDIALOG --backtitle "$OSNAME Installer" --title "Network Installation" --msgbox "Some installation files were not found on the boot volume. The next few screens will allow you to configure networking so that they can be downloaded from the Internet." 0 0
-	bsdinstall netconfig || error
+	./bsdinstall netconfig || error
 	NETCONFIG_DONE=yes
 fi
 
@@ -313,12 +313,12 @@ exec 5>&-
 
 case "$PARTMODE" in
 "$msg_auto_zfs")	# ZFS
-	bsdinstall zfsboot || error "ZFS setup failed"
-	bsdinstall mount || error "Failed to mount filesystem"
+	./bsdinstall zfsboot || error "ZFS setup failed"
+	./bsdinstall mount || error "Failed to mount filesystem"
 	;;
 "$msg_auto_ufs")	# Guided UFS
-	bsdinstall autopart || error "Partitioning error"
-	bsdinstall mount || error "Failed to mount filesystem"
+	./bsdinstall autopart || error "Partitioning error"
+	./bsdinstall mount || error "Failed to mount filesystem"
 	;;
 "$msg_shell")		# Shell
 	clear
@@ -328,11 +328,11 @@ case "$PARTMODE" in
 "$msg_manual")		# Manual
 	if f_isset debugFile; then
 		# Give partedit the path to our logfile so it can append
-		BSDINSTALL_LOG="${debugFile#+}" bsdinstall partedit || error "Partitioning error"
+		BSDINSTALL_LOG="${debugFile#+}" ./bsdinstall partedit || error "Partitioning error"
 	else
-		bsdinstall partedit || error "Partitioning error"
+		./bsdinstall partedit || error "Partitioning error"
 	fi
-	bsdinstall mount || error "Failed to mount filesystem"
+	./bsdinstall mount || error "Failed to mount filesystem"
 	;;
 *)
 	error "Unknown partitioning mode"
@@ -349,11 +349,11 @@ if [ -n "$FETCH_DISTRIBUTIONS" ]; then
 
 	[ $FETCH_RESULT -ne 0 ] && error "Could not fetch remote distributions"
 fi
-bsdinstall checksum || error "Distribution checksum failed"
-bsdinstall distextract || error "Distribution extract failed"
+./bsdinstall checksum || error "Distribution checksum failed"
+./bsdinstall distextract || error "Distribution extract failed"
 
 # Set up boot loader
-bsdinstall bootconfig || error "Failed to configure bootloader"
+./bsdinstall bootconfig || error "Failed to configure bootloader"
 
 [ -f $PREFIX/libexec/bsdinstall/local.pre-configure ] && f_dprintf "Running local.pre-configure" && sh $PREFIX/libexec/bsdinstall/local.pre-configure "$BSDINSTALL_CHROOT"
 
@@ -361,19 +361,19 @@ bsdinstall rootpass || error "Could not set root password"
 
 trap true SIGINT	# This section is optional
 if [ "$NETCONFIG_DONE" != yes ]; then
-	bsdinstall netconfig	# Don't check for errors -- the user may cancel
+	./bsdinstall netconfig	# Don't check for errors -- the user may cancel
 fi
-[ -z "$BSDINSTALL_SKIP_TIME" ] && bsdinstall time
-[ -z "$BSDINSTALL_SKIP_SERVICES" ] && bsdinstall services
-[ -z "$BSDINSTALL_SKIP_HARDENING" ] && bsdinstall hardening
+[ -z "$BSDINSTALL_SKIP_TIME" ] && ./bsdinstall time
+[ -z "$BSDINSTALL_SKIP_SERVICES" ] && ./bsdinstall services
+[ -z "$BSDINSTALL_SKIP_HARDENING" ] && ./bsdinstall hardening
 
 [ -z "$BSDINSTALL_SKIP_USERS" ] && $BSDDIALOG --backtitle "$OSNAME Installer" \
 	--title "Add User Accounts" --yesno \
     "Would you like to add users to the installed system now?" 0 0 && \
-    bsdinstall adduser
+    ./bsdinstall adduser
 
 # Allow user to change his mind
-[ -z "$BSDINSTALL_SKIP_FINALCONFIG" ] && bsdinstall finalconfig
+[ -z "$BSDINSTALL_SKIP_FINALCONFIG" ] && ./bsdinstall finalconfig
 
 trap error SIGINT	# SIGINT is bad again
 bsdinstall config  || error "Failed to save config"
@@ -382,7 +382,7 @@ if [ ! -z "$BSDINSTALL_FETCHDEST" ]; then
 	rm -rf "$BSDINSTALL_FETCHDEST"
 fi
 
-[ -f /usr/libexec/bsdinstall/local.post-configure ] && f_dprintf "Running local.post-configure" && sh /usr/libexec/bsdinstall/local.post-configure "$BSDINSTALL_CHROOT"
+[ -f $PREFIX/libexec/bsdinstall/local.post-configure ] && f_dprintf "Running local.post-configure" && sh $PREFIX/libexec/bsdinstall/local.post-configure "$BSDINSTALL_CHROOT"
 
 if [ -z "$BSDINSTALL_SKIP_MANUAL" ]; then
 	$BSDDIALOG --backtitle "$OSNAME Installer" --title "Manual Configuration" \
@@ -396,8 +396,8 @@ if [ -z "$BSDINSTALL_SKIP_MANUAL" ]; then
 	fi
 fi
 
-bsdinstall entropy
-bsdinstall umount
+./bsdinstall entropy
+./bsdinstall umount
 
 f_dprintf "Installation Completed at %s" "$( date )"
 
diff --git a/scripts/jail b/scripts/jail
--- a/scripts/jail
+++ b/scripts/jail
@@ -119,30 +119,30 @@ if [ -n "$FETCH_DISTRIBUTIONS" -a -z "$BSDINSTALL_DISTSITE" ]; then
 fi
 
 if [ ! -z "$FETCH_DISTRIBUTIONS" ]; then
-	bsdinstall distfetch || error "Failed to fetch distribution"
+	./bsdinstall distfetch || error "Failed to fetch distribution"
 fi
 
-bsdinstall checksum || error "Distribution checksum failed"
-bsdinstall distextract || error "Distribution extract failed"
+./bsdinstall checksum || error "Distribution checksum failed"
+./bsdinstall distextract || error "Distribution extract failed"
 
 if [ ! "$nonInteractive" == "YES" ]
 then
-    bsdinstall rootpass || error "Could not set root password"
+    ./bsdinstall rootpass || error "Could not set root password"
 fi
 
 trap true SIGINT	# This section is optional
 
 if [ ! "$nonInteractive" == "YES" ]
 then
-bsdinstall services
+	./bsdinstall services
 
-    $BSDDIALOG --backtitle "$OSNAME Installer" --title "Add User Accounts" --yesno \
-        "Would you like to add users to the installed system now?" 0 0 && \
-        bsdinstall adduser
+	$BSDDIALOG --backtitle "$OSNAME Installer" --title "Add User Accounts" --yesno \
+		"Would you like to add users to the installed system now?" 0 0 && \
+	./bsdinstall adduser
 fi
 
 trap error SIGINT	# SIGINT is bad again
-bsdinstall config  || error "Failed to save config"
+./bsdinstall config  || error "Failed to save config"
 cp /etc/resolv.conf $1/etc
 cp /etc/localtime $1/etc
 cp /var/db/zoneinfo $1/var/db
